modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="mana_box"
version="${file.jarVersion}"
displayName="ManaBox"
authors="edebe"
[[dependencies.mana_box]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mana_box]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mana_box]]
    modId="botania"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
